import '../Data/Bajaj/Maintenance/Ampara.dart';
import '../Data/Bajaj/Maintenance/Anuradapura.dart';
import '../Data/Bajaj/Maintenance/Badulla.dart';
import '../Data/Bajaj/Maintenance/Batticaloa.dart';
import '../Data/Bajaj/Maintenance/Colombo.dart';
import '../Data/Bajaj/Maintenance/Galle.dart';
import '../Data/Bajaj/Maintenance/Gampaha.dart';
import '../Data/Bajaj/Maintenance/Hambantota.dart';
import '../Data/Bajaj/Maintenance/Jaffna.dart';
import '../Data/Bajaj/Maintenance/Kalutara.dart';
import '../Data/Bajaj/Maintenance/Kandy.dart';
import '../Data/Bajaj/Maintenance/Kegalle.dart';
import '../Data/Bajaj/Maintenance/Kilinochchi.dart';
import '../Data/Bajaj/Maintenance/Kurunagala.dart';
import '../Data/Bajaj/Maintenance/Mannar.dart';
import '../Data/Bajaj/Maintenance/Matale.dart';
import '../Data/Bajaj/Maintenance/Matara.dart';
import '../Data/Bajaj/Maintenance/Monaragala.dart';
import '../Data/Bajaj/Maintenance/Mullaitivu.dart';
import '../Data/Bajaj/Maintenance/Nuwaraeliya.dart';
import '../Data/Bajaj/Maintenance/Polonnaruwa.dart';
import '../Data/Bajaj/Maintenance/Puttalam.dart';
import '../Data/Bajaj/Maintenance/Rathnapura.dart';
import '../Data/Bajaj/Maintenance/Trincomalee.dart';
import '../Data/Bajaj/Maintenance/Vavuniya.dart';

import '../Data/Bajaj/SpareParts/Ampara.dart';
import '../Data/Bajaj/SpareParts/Anuradapura.dart';
import '../Data/Bajaj/SpareParts/Badulla.dart';
import '../Data/Bajaj/SpareParts/Batticaloa.dart';
import '../Data/Bajaj/SpareParts/Colombo.dart';
import '../Data/Bajaj/SpareParts/Galle.dart';
import '../Data/Bajaj/SpareParts/Gampaha.dart';
import '../Data/Bajaj/SpareParts/Hambantota.dart';
import '../Data/Bajaj/SpareParts/Jaffna.dart';
import '../Data/Bajaj/SpareParts/Kalutara.dart';
import '../Data/Bajaj/SpareParts/Kandy.dart';
import '../Data/Bajaj/SpareParts/Kegalle.dart';
import '../Data/Bajaj/SpareParts/Kilinochchi.dart';
import '../Data/Bajaj/SpareParts/Kurunagala.dart';
import '../Data/Bajaj/SpareParts/Mannar.dart';
import '../Data/Bajaj/SpareParts/Matale.dart';
import '../Data/Bajaj/SpareParts/Matara.dart';
import '../Data/Bajaj/SpareParts/Monaragala.dart';
import '../Data/Bajaj/SpareParts/Mullaitivu.dart';
import '../Data/Bajaj/SpareParts/Nuwaraeliya.dart';
import '../Data/Bajaj/SpareParts/Polonnaruwa.dart';
import '../Data/Bajaj/SpareParts/Puttalam.dart';
import '../Data/Bajaj/SpareParts/Rathnapura.dart';
import '../Data/Bajaj/SpareParts/Trincomalee.dart';
import '../Data/Bajaj/SpareParts/Vavuniya.dart';

import '../Data/Honda/Maintenance/Ampara.dart';
import '../Data/Honda/Maintenance/Anuradapura.dart';
import '../Data/Honda/Maintenance/Badulla.dart';
import '../Data/Honda/Maintenance/Batticaloa.dart';
import '../Data/Honda/Maintenance/Colombo.dart';
import '../Data/Honda/Maintenance/Galle.dart';
import '../Data/Honda/Maintenance/Gampaha.dart';
import '../Data/Honda/Maintenance/Hambantota.dart';
import '../Data/Honda/Maintenance/Jaffna.dart';
import '../Data/Honda/Maintenance/Kalutara.dart';
import '../Data/Honda/Maintenance/Kandy.dart';
import '../Data/Honda/Maintenance/Kegalle.dart';
import '../Data/Honda/Maintenance/Kilinochchi.dart';
import '../Data/Honda/Maintenance/Kurunagala.dart';
import '../Data/Honda/Maintenance/Mannar.dart';
import '../Data/Honda/Maintenance/Matale.dart';
import '../Data/Honda/Maintenance/Matara.dart';
import '../Data/Honda/Maintenance/Monaragala.dart';
import '../Data/Honda/Maintenance/Mullaitivu.dart';
import '../Data/Honda/Maintenance/Nuwaraeliya.dart';
import '../Data/Honda/Maintenance/Polonnaruwa.dart';
import '../Data/Honda/Maintenance/Puttalam.dart';
import '../Data/Honda/Maintenance/Rathnapura.dart';
import '../Data/Honda/Maintenance/Trincomalee.dart';
import '../Data/Honda/Maintenance/Vavuniya.dart';

// Honda SpareParts Imports
import '../Data/Honda/SpareParts/Ampara.dart';
import '../Data/Honda/SpareParts/Anuradapura.dart';
import '../Data/Honda/SpareParts/Badulla.dart';
import '../Data/Honda/SpareParts/Batticaloa.dart';
import '../Data/Honda/SpareParts/Colombo.dart';
import '../Data/Honda/SpareParts/Galle.dart';
import '../Data/Honda/SpareParts/Gampaha.dart';
import '../Data/Honda/SpareParts/Hambantota.dart';
import '../Data/Honda/SpareParts/Jaffna.dart';
import '../Data/Honda/SpareParts/Kalutara.dart';
import '../Data/Honda/SpareParts/Kandy.dart';
import '../Data/Honda/SpareParts/Kegalle.dart';
import '../Data/Honda/SpareParts/Kilinochchi.dart';
import '../Data/Honda/SpareParts/Kurunagala.dart';
import '../Data/Honda/SpareParts/Mannar.dart';
import '../Data/Honda/SpareParts/Matale.dart';
import '../Data/Honda/SpareParts/Matara.dart';
import '../Data/Honda/SpareParts/Monaragala.dart';
import '../Data/Honda/SpareParts/Mullaitivu.dart';
import '../Data/Honda/SpareParts/Nuwaraeliya.dart';
import '../Data/Honda/SpareParts/Polonnaruwa.dart';
import '../Data/Honda/SpareParts/Puttalam.dart';
import '../Data/Honda/SpareParts/Rathnapura.dart';
import '../Data/Honda/SpareParts/Trincomalee.dart';
import '../Data/Honda/SpareParts/Vavuniya.dart';

import '../Data/Suzuki/Maintenance/Ampara.dart';
import '../Data/Suzuki/Maintenance/Anuradapura.dart';
import '../Data/Suzuki/Maintenance/Badulla.dart';
import '../Data/Suzuki/Maintenance/Batticaloa.dart';
import '../Data/Suzuki/Maintenance/Colombo.dart';
import '../Data/Suzuki/Maintenance/Galle.dart';
import '../Data/Suzuki/Maintenance/Gampaha.dart';
import '../Data/Suzuki/Maintenance/Hambantota.dart';
import '../Data/Suzuki/Maintenance/Jaffna.dart';
import '../Data/Suzuki/Maintenance/Kalutara.dart';
import '../Data/Suzuki/Maintenance/Kandy.dart';
import '../Data/Suzuki/Maintenance/Kegalle.dart';
import '../Data/Suzuki/Maintenance/Kilinochchi.dart';
import '../Data/Suzuki/Maintenance/Kurunagala.dart';
import '../Data/Suzuki/Maintenance/Mannar.dart';
import '../Data/Suzuki/Maintenance/Matale.dart';
import '../Data/Suzuki/Maintenance/Matara.dart';
import '../Data/Suzuki/Maintenance/Monaragala.dart';
import '../Data/Suzuki/Maintenance/Mullaitivu.dart';
import '../Data/Suzuki/Maintenance/Nuwaraeliya.dart';
import '../Data/Suzuki/Maintenance/Polonnaruwa.dart';
import '../Data/Suzuki/Maintenance/Puttalam.dart';
import '../Data/Suzuki/Maintenance/Rathnapura.dart';
import '../Data/Suzuki/Maintenance/Trincomalee.dart';
import '../Data/Suzuki/Maintenance/Vavuniya.dart';

// Suzuki SpareParts Imports
import '../Data/Suzuki/SpareParts/Ampara.dart';
import '../Data/Suzuki/SpareParts/Anuradapura.dart';
import '../Data/Suzuki/SpareParts/Badulla.dart';
import '../Data/Suzuki/SpareParts/Batticaloa.dart';
import '../Data/Suzuki/SpareParts/Colombo.dart';
import '../Data/Suzuki/SpareParts/Galle.dart';
import '../Data/Suzuki/SpareParts/Gampaha.dart';
import '../Data/Suzuki/SpareParts/Hambantota.dart';
import '../Data/Suzuki/SpareParts/Jaffna.dart';
import '../Data/Suzuki/SpareParts/Kalutara.dart';
import '../Data/Suzuki/SpareParts/Kandy.dart';
import '../Data/Suzuki/SpareParts/Kegalle.dart';
import '../Data/Suzuki/SpareParts/Kilinochchi.dart';
import '../Data/Suzuki/SpareParts/Kurunagala.dart';
import '../Data/Suzuki/SpareParts/Mannar.dart';
import '../Data/Suzuki/SpareParts/Matale.dart';
import '../Data/Suzuki/SpareParts/Matara.dart';
import '../Data/Suzuki/SpareParts/Monaragala.dart';
import '../Data/Suzuki/SpareParts/Mullaitivu.dart';
import '../Data/Suzuki/SpareParts/Nuwaraeliya.dart';
import '../Data/Suzuki/SpareParts/Polonnaruwa.dart';
import '../Data/Suzuki/SpareParts/Puttalam.dart';
import '../Data/Suzuki/SpareParts/Rathnapura.dart';
import '../Data/Suzuki/SpareParts/Trincomalee.dart';
import '../Data/Suzuki/SpareParts/Vavuniya.dart';

import '../Data/Toyota/Maintenance/Ampara.dart';
import '../Data/Toyota/Maintenance/Anuradapura.dart';
import '../Data/Toyota/Maintenance/Badulla.dart';
import '../Data/Toyota/Maintenance/Batticaloa.dart';
import '../Data/Toyota/Maintenance/Colombo.dart';
import '../Data/Toyota/Maintenance/Galle.dart';
import '../Data/Toyota/Maintenance/Gampaha.dart';
import '../Data/Toyota/Maintenance/Hambantota.dart';
import '../Data/Toyota/Maintenance/Jaffna.dart';
import '../Data/Toyota/Maintenance/Kalutara.dart';
import '../Data/Toyota/Maintenance/Kandy.dart';
import '../Data/Toyota/Maintenance/Kegalle.dart';
import '../Data/Toyota/Maintenance/Kilinochchi.dart';
import '../Data/Toyota/Maintenance/Kurunagala.dart';
import '../Data/Toyota/Maintenance/Mannar.dart';
import '../Data/Toyota/Maintenance/Matale.dart';
import '../Data/Toyota/Maintenance/Matara.dart';
import '../Data/Toyota/Maintenance/Monaragala.dart';
import '../Data/Toyota/Maintenance/Mullaitivu.dart';
import '../Data/Toyota/Maintenance/Nuwaraeliya.dart';
import '../Data/Toyota/Maintenance/Polonnaruwa.dart';
import '../Data/Toyota/Maintenance/Puttalam.dart';
import '../Data/Toyota/Maintenance/Rathnapura.dart';
import '../Data/Toyota/Maintenance/Trincomalee.dart';
import '../Data/Toyota/Maintenance/Vavuniya.dart';

// Toyota SpareParts Imports
import '../Data/Toyota/SpareParts/Ampara.dart';
import '../Data/Toyota/SpareParts/Anuradapura.dart';
import '../Data/Toyota/SpareParts/Badulla.dart';
import '../Data/Toyota/SpareParts/Batticaloa.dart';
import '../Data/Toyota/SpareParts/Colombo.dart';
import '../Data/Toyota/SpareParts/Galle.dart';
import '../Data/Toyota/SpareParts/Gampaha.dart';
import '../Data/Toyota/SpareParts/Hambantota.dart';
import '../Data/Toyota/SpareParts/Jaffna.dart';
import '../Data/Toyota/SpareParts/Kalutara.dart';
import '../Data/Toyota/SpareParts/Kandy.dart';
import '../Data/Toyota/SpareParts/Kegalle.dart';
import '../Data/Toyota/SpareParts/Kilinochchi.dart';
import '../Data/Toyota/SpareParts/Kurunagala.dart';
import '../Data/Toyota/SpareParts/Mannar.dart';
import '../Data/Toyota/SpareParts/Matale.dart';
import '../Data/Toyota/SpareParts/Matara.dart';
import '../Data/Toyota/SpareParts/Monaragala.dart';
import '../Data/Toyota/SpareParts/Mullaitivu.dart';
import '../Data/Toyota/SpareParts/Nuwaraeliya.dart';
import '../Data/Toyota/SpareParts/Polonnaruwa.dart';
import '../Data/Toyota/SpareParts/Puttalam.dart';
import '../Data/Toyota/SpareParts/Rathnapura.dart';
import '../Data/Toyota/SpareParts/Trincomalee.dart';
import '../Data/Toyota/SpareParts/Vavuniya.dart';

class DataClass {
  late Map<String, dynamic> listofproviderslist = {
    'BajajMaintenanceAmpara': maintanceAmpara,
    'BajajMaintenanceAnuradhapura': maintanceAnuradapura,
    'BajajMaintenanceBadulla': maintanceBadulla,
    'BajajMaintenanceBatticaloa': maintanceBatticaloa,
    'BajajMaintenanceColombo': maintanceColombo,
    'BajajMaintenanceGalle': maintanceGalle,
    'BajajMaintenanceGampaha': maintanceGampaha,
    'BajajMaintenanceHambantota': maintanceHambantota,
    'BajajMaintenanceJaffna': maintanceJaffna,
    'BajajMaintenanceKalutara': maintanceKalutara,
    'BajajMaintenanceKandy': maintanceKandy,
    'BajajMaintenanceKegalle': maintanceKegalle,
    'BajajMaintenanceKilinochchi': maintanceKilinochchi,
    'BajajMaintenanceKurunegala': maintanceKurunagala,
    'BajajMaintenanceMannar': maintanceMannar,
    'BajajMaintenanceMatale': maintanceMatale,
    'BajajMaintenanceMatara': maintanceMatara,
    'BajajMaintenanceMonaragala': maintanceMonaragala,
    'BajajMaintenanceMullaitivu': maintanceMullaitivu,
    'BajajMaintenanceNuwara Eliya': maintanceNuwaraeliya,
    'BajajMaintenancePolonnaruwa': maintancePolonnaruwa,
    'BajajMaintenancePuttalam': maintancePuttalam,
    'BajajMaintenanceRathnapura': maintanceRathnapura,
    'BajajMaintenanceTrincomalee': maintanceTrincomalee,
    'BajajMaintenanceVavuniya': maintanceVavuniya,

    'BajajSparePartsAmpara': BajajSparePartsAmpara,
    'BajajSparePartsAnuradhapura': BajajSparePartsAnuradapura,
    'BajajSparePartsBadulla': BajajSparePartsBadulla,
    'BajajSparePartsBatticaloa': BajajSparePartsBatticaloa,
    'BajajSparePartsColombo': BajajSparePartsColombo,
    'BajajSparePartsGalle': BajajSparePartsGalle,
    'BajajSparePartsGampaha': BajajSparePartsGampaha,
    'BajajSparePartsHambantota': BajajSparePartsHambantota,
    'BajajSparePartsJaffna': BajajSparePartsJaffna,
    'BajajSparePartsKalutara': BajajSparePartsKalutara,
    'BajajSparePartsKandy': BajajSparePartsKandy,
    'BajajSparePartsKegalle': BajajSparePartsKegalle,
    'BajajSparePartsKilinochchi': BajajSparePartsKilinochchi,
    'BajajSparePartsKurunegala': BajajSparePartsKurunagala,
    'BajajSparePartsMannar': BajajSparePartsMannar,
    'BajajSparePartsMatale': BajajSparePartsMatale,
    'BajajSparePartsMatara': BajajSparePartsMatara,
    'BajajSparePartsMonaragala': BajajSparePartsMonaragala,
    'BajajSparePartsMullaitivu': BajajSparePartsMullaitivu,
    'BajajSparePartsNuwara Eliya': BajajSparePartsNuwaraeliya,
    'BajajSparePartsPolonnaruwa': BajajSparePartsPolonnaruwa,
    'BajajSparePartsPuttalam': BajajSparePartsPuttalam,
    'BajajSparePartsRathnapura': BajajSparePartsRathnapura,
    'BajajSparePartsTrincomalee': BajajSparePartsTrincomalee,
    'BajajSparePartsVavuniya': BajajSparePartsVavuniya,

    'HondaMaintenanceAmpara': HondaMaintanceAmpara,
    'HondaMaintenanceAnuradhapura': HondaMaintanceAnuradapura,
    'HondaMaintenanceBadulla': HondaMaintanceBadulla,
    'HondaMaintenanceBatticaloa': HondaMaintanceBatticaloa,
    'HondaMaintenanceColombo': HondaMaintanceColombo,
    'HondaMaintenanceGalle': HondaMaintanceGalle,
    'HondaMaintenanceGampaha': HondaMaintanceGampaha,
    'HondaMaintenanceHambantota': HondaMaintanceHambantota,
    'HondaMaintenanceJaffna': HondaMaintanceJaffna,
    'HondaMaintenanceKalutara': HondaMaintanceKalutara,
    'HondaMaintenanceKandy': HondaMaintanceKandy,
    'HondaMaintenanceKegalle': HondaMaintanceKegalle,
    'HondaMaintenanceKilinochchi': HondaMaintanceKilinochchi,
    'HondaMaintenanceKurunegala': HondaMaintanceKurunagala,
    'HondaMaintenanceMannar': HondaMaintanceMannar,
    'HondaMaintenanceMatale': HondaMaintanceMatale,
    'HondaMaintenanceMatara': HondaMaintanceMatara,
    'HondaMaintenanceMonaragala': HondaMaintanceMonaragala,
    'HondaMaintenanceMullaitivu': HondaMaintanceMullaitivu,
    'HondaMaintenanceNuwara Eliya': HondaMaintanceNuwaraeliya,
    'HondaMaintenancePolonnaruwa': HondaMaintancePolonnaruwa,
    'HondaMaintenancePuttalam': HondaMaintancePuttalam,
    'HondaMaintenanceRathnapura': HondaMaintanceRathnapura,
    'HondaMaintenanceTrincomalee': HondaMaintanceTrincomalee,
    'HondaMaintenanceVavuniya': HondaMaintanceVavuniya,

    // Honda SpareParts entries
    'HondaSparePartsAmpara': HondaSparePartsAmpara,
    'HondaSparePartsAnuradhapura': HondaSparePartsAnuradapura,
    'HondaSparePartsBadulla': HondaSparePartsBadulla,
    'HondaSparePartsBatticaloa': HondaSparePartsBatticaloa,
    'HondaSparePartsColombo': HondaSparePartsColombo,
    'HondaSparePartsGalle': HondaSparePartsGalle,
    'HondaSparePartsGampaha': HondaSparePartsGampaha,
    'HondaSparePartsHambantota': HondaSparePartsHambantota,
    'HondaSparePartsJaffna': HondaSparePartsJaffna,
    'HondaSparePartsKalutara': HondaSparePartsKalutara,
    'HondaSparePartsKandy': HondaSparePartsKandy,
    'HondaSparePartsKegalle': HondaSparePartsKegalle,
    'HondaSparePartsKilinochchi': HondaSparePartsKilinochchi,
    'HondaSparePartsKurunegala': HondaSparePartsKurunagala,
    'HondaSparePartsMannar': HondaSparePartsMannar,
    'HondaSparePartsMatale': HondaSparePartsMatale,
    'HondaSparePartsMatara': HondaSparePartsMatara,
    'HondaSparePartsMonaragala': HondaSparePartsMonaragala,
    'HondaSparePartsMullaitivu': HondaSparePartsMullaitivu,
    'HondaSparePartsNuwara Eliya': HondaSparePartsNuwaraeliya,
    'HondaSparePartsPolonnaruwa': HondaSparePartsPolonnaruwa,
    'HondaSparePartsPuttalam': HondaSparePartsPuttalam,
    'HondaSparePartsRathnapura': HondaSparePartsRathnapura,
    'HondaSparePartsTrincomalee': HondaSparePartsTrincomalee,
    'HondaSparePartsVavuniya': HondaSparePartsVavuniya,

    'SuzukiMaintenanceAmpara': SuzukiMaintenanceAmpara,
    'SuzukiMaintenanceAnuradhapura': SuzukiMaintenanceAnuradapura,
    'SuzukiMaintenanceBadulla': SuzukiMaintenanceBadulla,
    'SuzukiMaintenanceBatticaloa': SuzukiMaintenanceBatticaloa,
    'SuzukiMaintenanceColombo': SuzukiMaintenanceColombo,
    'SuzukiMaintenanceGalle': SuzukiMaintenanceGalle,
    'SuzukiMaintenanceGampaha': SuzukiMaintenanceGampaha,
    'SuzukiMaintenanceHambantota': SuzukiMaintenanceHambantota,
    'SuzukiMaintenanceJaffna': SuzukiMaintenanceJaffna,
    'SuzukiMaintenanceKalutara': SuzukiMaintenanceKalutara,
    'SuzukiMaintenanceKandy': SuzukiMaintenanceKandy,
    'SuzukiMaintenanceKegalle': SuzukiMaintenanceKegalle,
    'SuzukiMaintenanceKilinochchi': SuzukiMaintenanceKilinochchi,
    'SuzukiMaintenanceKurunegala': SuzukiMaintenanceKurunagala,
    'SuzukiMaintenanceMannar': SuzukiMaintenanceMannar,
    'SuzukiMaintenanceMatale': SuzukiMaintenanceMatale,
    'SuzukiMaintenanceMatara': SuzukiMaintenanceMatara,
    'SuzukiMaintenanceMonaragala': SuzukiMaintenanceMonaragala,
    'SuzukiMaintenanceMullaitivu': SuzukiMaintenanceMullaitivu,
    'SuzukiMaintenanceNuwara Eliya': SuzukiMaintenanceNuwaraeliya,
    'SuzukiMaintenancePolonnaruwa': SuzukiMaintenancePolonnaruwa,
    'SuzukiMaintenancePuttalam': SuzukiMaintenancePuttalam,
    'SuzukiMaintenanceRathnapura': SuzukiMaintenanceRathnapura,
    'SuzukiMaintenanceTrincomalee': SuzukiMaintenanceTrincomalee,
    'SuzukiMaintenanceVavuniya': SuzukiMaintenanceVavuniya,

    // Suzuki SpareParts entries
    'SuzukiSparePartsAmpara': SuzukiSparePartsAmpara,
    'SuzukiSparePartsAnuradhapura': SuzukiSparePartsAnuradapura,
    'SuzukiSparePartsBadulla': SuzukiSparePartsBadulla,
    'SuzukiSparePartsBatticaloa': SuzukiSparePartsBatticaloa,
    'SuzukiSparePartsColombo': SuzukiSparePartsColombo,
    'SuzukiSparePartsGalle': SuzukiSparePartsGalle,
    'SuzukiSparePartsGampaha': SuzukiSparePartsGampaha,
    'SuzukiSparePartsHambantota': SuzukiSparePartsHambantota,
    'SuzukiSparePartsJaffna': SuzukiSparePartsJaffna,
    'SuzukiSparePartsKalutara': SuzukiSparePartsKalutara,
    'SuzukiSparePartsKandy': SuzukiSparePartsKandy,
    'SuzukiSparePartsKegalle': SuzukiSparePartsKegalle,
    'SuzukiSparePartsKilinochchi': SuzukiSparePartsKilinochchi,
    'SuzukiSparePartsKurunegala': SuzukiSparePartsKurunagala,
    'SuzukiSparePartsMannar': SuzukiSparePartsMannar,
    'SuzukiSparePartsMatale': SuzukiSparePartsMatale,
    'SuzukiSparePartsMatara': SuzukiSparePartsMatara,
    'SuzukiSparePartsMonaragala': SuzukiSparePartsMonaragala,
    'SuzukiSparePartsMullaitivu': SuzukiSparePartsMullaitivu,
    'SuzukiSparePartsNuwara Eliya': SuzukiSparePartsNuwaraeliya,
    'SuzukiSparePartsPolonnaruwa': SuzukiSparePartsPolonnaruwa,
    'SuzukiSparePartsPuttalam': SuzukiSparePartsPuttalam,
    'SuzukiSparePartsRathnapura': SuzukiSparePartsRathnapura,
    'SuzukiSparePartsTrincomalee': SuzukiSparePartsTrincomalee,
    'SuzukiSparePartsVavuniya': SuzukiSparePartsVavuniya,

    'ToyotaMaintenanceAmpara': ToyotaMaintenanceAmpara,
    'ToyotaMaintenanceAnuradhapura': ToyotaMaintenanceAnuradapura,
    'ToyotaMaintenanceBadulla': ToyotaMaintenanceBadulla,
    'ToyotaMaintenanceBatticaloa': ToyotaMaintenanceBatticaloa,
    'ToyotaMaintenanceColombo': ToyotaMaintenanceColombo,
    'ToyotaMaintenanceGalle': ToyotaMaintenanceGalle,
    'ToyotaMaintenanceGampaha': ToyotaMaintenanceGampaha,
    'ToyotaMaintenanceHambantota': ToyotaMaintenanceHambantota,
    'ToyotaMaintenanceJaffna': ToyotaMaintenanceJaffna,
    'ToyotaMaintenanceKalutara': ToyotaMaintenanceKalutara,
    'ToyotaMaintenanceKandy': ToyotaMaintenanceKandy,
    'ToyotaMaintenanceKegalle': ToyotaMaintenanceKegalle,
    'ToyotaMaintenanceKilinochchi': ToyotaMaintenanceKilinochchi,
    'ToyotaMaintenanceKurunegala': ToyotaMaintenanceKurunagala,
    'ToyotaMaintenanceMannar': ToyotaMaintenanceMannar,
    'ToyotaMaintenanceMatale': ToyotaMaintenanceMatale,
    'ToyotaMaintenanceMatara': ToyotaMaintenanceMatara,
    'ToyotaMaintenanceMonaragala': ToyotaMaintenanceMonaragala,
    'ToyotaMaintenanceMullaitivu': ToyotaMaintenanceMullaitivu,
    'ToyotaMaintenanceNuwara Eliya': ToyotaMaintenanceNuwaraeliya,
    'ToyotaMaintenancePolonnaruwa': ToyotaMaintenancePolonnaruwa,
    'ToyotaMaintenancePuttalam': ToyotaMaintenancePuttalam,
    'ToyotaMaintenanceRathnapura': ToyotaMaintenanceRathnapura,
    'ToyotaMaintenanceTrincomalee': ToyotaMaintenanceTrincomalee,
    'ToyotaMaintenanceVavuniya': ToyotaMaintenanceVavuniya,

    // Toyota SpareParts entries
    'ToyotaSparePartsAmpara': ToyotaSparePartsAmpara,
    'ToyotaSparePartsAnuradhapura': ToyotaSparePartsAnuradapura,
    'ToyotaSparePartsBadulla': ToyotaSparePartsBadulla,
    'ToyotaSparePartsBatticaloa': ToyotaSparePartsBatticaloa,
    'ToyotaSparePartsColombo': ToyotaSparePartsColombo,
    'ToyotaSparePartsGalle': ToyotaSparePartsGalle,
    'ToyotaSparePartsGampaha': ToyotaSparePartsGampaha,
    'ToyotaSparePartsHambantota': ToyotaSparePartsHambantota,
    'ToyotaSparePartsJaffna': ToyotaSparePartsJaffna,
    'ToyotaSparePartsKalutara': ToyotaSparePartsKalutara,
    'ToyotaSparePartsKandy': ToyotaSparePartsKandy,
    'ToyotaSparePartsKegalle': ToyotaSparePartsKegalle,
    'ToyotaSparePartsKilinochchi': ToyotaSparePartsKilinochchi,
    'ToyotaSparePartsKurunegala': ToyotaSparePartsKurunagala,
    'ToyotaSparePartsMannar': ToyotaSparePartsMannar,
    'ToyotaSparePartsMatale': ToyotaSparePartsMatale,
    'ToyotaSparePartsMatara': ToyotaSparePartsMatara,
    'ToyotaSparePartsMonaragala': ToyotaSparePartsMonaragala,
    'ToyotaSparePartsMullaitivu': ToyotaSparePartsMullaitivu,
    'ToyotaSparePartsNuwara Eliya': ToyotaSparePartsNuwaraeliya,
    'ToyotaSparePartsPolonnaruwa': ToyotaSparePartsPolonnaruwa,
    'ToyotaSparePartsPuttalam': ToyotaSparePartsPuttalam,
    'ToyotaSparePartsRathnapura': ToyotaSparePartsRathnapura,
    'ToyotaSparePartsTrincomalee': ToyotaSparePartsTrincomalee,
    'ToyotaSparePartsVavuniya': ToyotaSparePartsVavuniya,
  };

  List<Map<String, dynamic>> getListOfProviders(details) {
    List<Map<String, dynamic>> value = listofproviderslist[details] ?? 0;
    print(value);
    return value;
  }
}
